### ISSUE TITLE
Unable to run below Android 7

### ISSUE THREAD

**Issue by LaneAndms01** [hax0r31337/ProtoHax-Android#13]

**Comment by hax0r31337** [comment]
please be aware this is a **English-only repository**, and according to `app/build.gradle`, the lowest supported SDK version is 28 which is Android 9.   
We are retiring support for old devices in order to focus on improving the performance of our cheat for newer devices. We apologize for any inconvenience this may cause, and we thank you for your understanding.

**Comment by LaneAndms01** [comment]
😭😭😭
